############# Spanish navigation ##############

[[main]]
name = "Qué Ofrecemos"
url = "ofrecemos/"
weight = 1

[[main]]
name = "Especiales"
url = "especiales/"
weight = 2

[[main]]
name = "Conócenos"
url = "conocenos/"
weight = 3

[[main]]
name = "Trabajos Realizados"
url = "trabajos-realizados/"
weight = 4