#################### default parameters ################################
# favicon
favicon = "images/favicon.png"
# logo
logo = "images/pistakiavera-logo.svg"
# use `px` or `x` with logo_width, example: "100px".
# Note: logo_width is not work with .svg file
logo_width = "205"
logo_height = "50"
# logo text will only show when logo is missing.
logo_text = "Pistakiavera ® | Believe it!"
# navbar fixed to top
navbar_fixed = false
# OpenGraph / Twitter Card metadata
description = "Pistakiavera, Organizadora de eventos personalizados a medida frikis, infantiles, cumpleaños, empresas, pedidas en Madrid"
author = "Pistakiavera"
image = "images/logo-pistakiavera.png" # this image will be used as fallback if a page has no image of its own
# copyright
copyright = "Pistakiavera ® - Haz tus sueños realidad. Hecho con "

[contact.form]
enable = false

######### Footer - Redes Sociales de Pistakiavera #########
[[social]]
red_social = "Instagram - Pistakiavera"
icono = "instagram"
enlace = "https://www.instagram.com/pistakiavera/"


# cookies
[cookies]
enable = true
expire_days = 2
content = "Este sitio solo utiliza cookies de analítica. Si continúa utilizando este sitio web, acepta su uso."
button = "¡Acepto!"


# Whether to use [Netlify Forms](https://docs.netlify.com/forms/setup/)
# ---------------------------------------------------------------------
use_netlify = true
# Form action
## Fill in your Form ID URL for Formspree.io, e.g. `https://formspree.io/f/{form_id}`
## Ignored if `use_netlify = true` (custom [success page](https://docs.netlify.com/forms/setup/#success-messages) is already included) 
action = "#"
# Image on custom success page `/message_sent.html`
success_image = "images/paper-plane.svg"
# Esta en la ruta pista1\public\images
#success_image = "images/mensaje_enviado_pistakiavera.png"


# Preloader
[preloader]
enable = true
preloader = "jpg, png" # use jpg, png, svg or gif format.

# Navigation button
[navigation_button]
enable = false
label = "get a quote"
link = "contact"


# Tracking different tools Analytics
# ----------------------------------

# google tag manager, see https://developers.google.com/tag-manager/
google_tag_manager = "" # example: G-XXXXXXXXXX

# matomo tracking: see https://matomo.org/
[matomo]
enable = false
url = "" # your matomo url
id = "" # your matomo id

# baidu analytics: see https://tongji.baidu.com/
[baidu]
enable = false
analytics_id = "" # Your ID

# plausible analytics: see https://plausible.io/
# how-to -> https://plausible.io/docs/hugo-integration
[plausible]
enable = false
domain = "#" # yourdomain.com

# counter analytics: see https://counter.dev/setup.html
# HECHO: Usando esta APP de analítica free.
[counter]
enable = true
username = "FeliDev" # your username counter.dev

# site verifications
[site_verification]
google = "" # Your verification code
bing = "" # Your verification code
baidu = "" # Your verification code

# google map
[gmap]
enable = false
gmap_api = "xxxxxxxxx"
map_latitude = "xxxx"
map_longitude = "xxxx"
map_marker = "images/marker.png"

######################## sidebar widgets #########################
[widgets]
sidebar = ["recent_posts", "taxonomy_category", "taxonomy_tags"]
# available widget : categories,tags,recent-post